name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./API
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./API
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx
      working-directory: ./Subman.Tests

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
